<?php

/**
 * @file
 * Contains os2loop_user.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\os2loop_user\Helper\Helper;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function os2loop_user_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the os2loop_user module.
    case 'help.page.os2loop_user':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OS2Loop user') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_query_alter().
 *
 * @see \Drupal\os2loop_user\Helper\Helper::queryAlter()
 */
function os2loop_user_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  Drupal::service(Helper::class)->queryAlter($view, $query);
}

/**
 * Implements hook_form_alter().
 *
 * @see \Drupal\os2loop_user\Helper\Helper::alterForm()
 */
function os2loop_user_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  Drupal::service(Helper::class)->alterForm($form, $form_state, $form_id);
}
