<?php

/**
 * @file
 * Hooks for os2loop messages.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_insert().
 *
 * @see \Drupal\os2loop_messages\Helper\Helper::entityInsert()
 */
function os2loop_messages_entity_insert(EntityInterface $entity) {
  Drupal::service('os2loop_messages.helper')->entityInsert($entity);
}

/**
 * Implements hook_entity_update().
 *
 * @see \Drupal\os2loop_messages\Helper\Helper::entityUpdate()
 */
function os2loop_messages_entity_update(EntityInterface $entity) {
  Drupal::service('os2loop_messages.helper')->entityUpdate($entity);
}

/**
 * Implements hook_form_alter().
 *
 * @see \Drupal\os2loop_messages\Helper\Helper::formAlter()
 */
function os2loop_messages_form_alter(&$form, &$form_state, $form_id) {
  Drupal::service('os2loop_messages.helper')->formAlter($form, $form_id);
}
