<?php

/**
 * @file
 * Hooks for OS2Loop Mail notifications.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\os2loop_mail_notifications\Helper\Helper;
use Drupal\os2loop_mail_notifications\Helper\MailHelper;

/**
 * Implements hook_cron().
 *
 * @see \Drupal\os2loop_mail_notifications\Helper\Helper::cron()
 */
function os2loop_mail_notifications_cron() {
  Drupal::service(Helper::class)->cron();
}

/**
 * Implements hook_mail().
 *
 * @see \Drupal\os2loop_mail_notifications\Helper\MailHelper::mail()
 */
function os2loop_mail_notifications_mail($key, &$message, $params) {
  Drupal::service(MailHelper::class)->mail($key, $message, $params);
}

/**
 * Implements hook_tokens().
 *
 * @see \Drupal\os2loop_mail_notifications\Helper\MailHelper::tokens()
 */
function os2loop_mail_notifications_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  return Drupal::service(MailHelper::class)->tokens($type, $tokens, $data);
}

/**
 * Implements hook_token_info().
 *
 * @see \Drupal\os2loop_mail_notifications\Helper\MailHelper::tokenInfo()
 */
function os2loop_mail_notifications_token_info() {
  return Drupal::service(MailHelper::class)->tokenInfo();
}

/**
 * Implements hook_user_insert().
 *
 * @see \Drupal\os2loop_mail_notifications\Helper\Helper::userInsert()
 */
function os2loop_mail_notifications_user_insert(EntityInterface $entity) {
  return Drupal::service(Helper::class)->userInsert($entity);
}
