#!/usr/bin/env bash

if ! docker run --volume ${PWD}:/app --workdir /app itkdev/php8.1-fpm:latest composer coding-standards-check; then
  cat >&2 << EOF
Please fix any coding standards issues before commit'ing!
EOF
  exit 1
fi

if ! docker run --volume ${PWD}:/app --workdir /app node:16 yarn coding-standards-check; then
  cat >&2 << EOF
Please fix any coding standards issues before commit'ing!
EOF
  exit 1
fi

exit 0
