#!/usr/bin/env bash

dir=$(cd $(dirname "${BASH_SOURCE[0]}")/.. && pwd)

cd $dir


# https://drupal.stackexchange.com/a/173879


# Get all OS2Loop modules but os2loop_shared (which must be at end of list)
modules=$(ls web/profiles/custom/os2loop/modules/os2loop_*/os2loop_*.info.yml | xargs basename -s .info.yml | grep -v os2loop_shared)
# Append os2loop_shared
modules="$modules os2loop_shared"

for module in $modules; do
  echo $module
  mkdir -p web/profiles/custom/os2loop/modules/$module/config/install
  if compgen -G config/sync/*$module*.yml > /dev/null; then
    echo Moving files to web/profiles/custom/os2loop/modules/$module/config/install
    mv config/sync/*$module*.yml web/profiles/custom/os2loop/modules/$module/config/install
    cat <<EOF

Make sure that

dependencies:
  enforced:
    module:
      - $module

is set in one the config files in web/profiles/custom/os2loop/modules/$module/config/install

EOF

    # grep '^  enforced:$'
  else
    echo No config to move
  fi
  echo
done
