<?php

/**
 * @file
 * Hook implementations related to toc block module.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\os2loop_toc_block\Helper\Helper;

/**
 * Implements hook_node_view().
 *
 * Change display of node.
 *
 * @see \Drupal\os2loop_toc_block\Helper\Helper::nodeView()
 */
function os2loop_toc_block_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  Drupal::service(Helper::class)->nodeView($build, $node, $display, $view_mode);
}
