<?php

/**
 * @file
 * Code for the Loop documents feature.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;
use Drupal\node\NodeInterface;
use Drupal\os2loop_documents\Helper\CollectionHelper;

/**
 * Implements hook_help().
 */
function os2loop_documents_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the os2loop_documents module.
    case 'help.documents.os2loop_documents':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OS2Loop documents') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function os2loop_documents_form_node_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $node = $form_state->getformObject()->getEntity();
  if (isset($node)) {
    if ($node->getType() === CollectionHelper::CONTENT_TYPE_COLLECTION) {
      os2loop_documents_build_document_tree($form, $form_state, $node);
    }

    if (in_array($node->type, [
      'loop_documents_collection', 'loop_documents_document',
    ])) {
      if (isset($form['body'])) {
        // Remove text format selector.
        $language = $form['body']['#language'];
        $form['body'][$language]['0']['#format'] = 'loop_documents';
      }
      $form['#attached']['css'][] = drupal_get_path('module', 'loop_documents') . '/css/loop_documents.admin.css';
      $form['#attached']['js'][] = drupal_get_path('module', 'loop_documents') . '/js/loop_documents.admin.js';
      $form['#after_build'][] = 'loop_documents_after_build';
    }
  }
}

/**
 *
 */
function os2loop_documents_add_document_submit(array &$form, FormStateInterface $form_state) {
//  $documents = $form_state->getValue('os2loop_documents_documents')[0]['value'] ?? NULL;
//  $data = json_decode($documents, TRUE);
//  if (!is_array($data)) {
//    $data = [];
//  }
  $data = $form_state->get('documents') ?? [];
  $document_id = $form_state->getValue('document');
  $target_node = Node::load($document_id);
  if ($target_node) {
    // $data = json_decode('{"4":{"weight":"-10","id":"4","pid":"0"},"5":{"weight":"-10","id":"5","pid":"4"},"6":{"weight":"-9","id":"6","pid":"0"},"1":{"weight":"-8","id":"1","pid":"0"},"2":{"weight":"-10","id":"2","pid":"1"},"3":{"weight":"-10","id":"3","pid":"2"}}', true);
    $data[$target_node->id()] = [
      'weight' => 1000,
      'id' => $target_node->id(),
      'pid' => 0,
    ];

    // // header('content-type: text/plain'); echo var_export($documents, true); die(__FILE__.':'.__LINE__.':'.__METHOD__);
//    $form_state->setValue('os2loop_documents_documents', [['value' => json_encode($data)]]);
    $form_state->set('documents', $data);
    $form_state->setRebuild(TRUE);
  }
}

/**
 *
 */
function os2loop_documents_add_document_set(array &$form, FormStateInterface $form_state) {
  // Return [
  //     '#markup' => __METHOD__,
  //   ];
  //  return $form['os2loop_documents_documents'];.
  return $form['documents'];
}

function os2loop_documents_remove_document_submit(array &$form, FormStateInterface $form_state) {
  $trigger = $form_state->getTriggeringElement();
  $documentId = $trigger['#attributes']['data-document-id'] ?? NULL;
  if (null !== $documentId) {
    // Remove document from collection.
    // @todo remove children
    $node = $form_state->getformObject()->getEntity();
    $data = os2loop_documents_get_collection_documents($form_state, $node);
    if (isset($data[$documentId])) {
      unset($data[$documentId]);
      $form_state->set('documents', $data);
      $form_state->setRebuild(TRUE);
    }
  }
}

function os2loop_documents_remove_document_set(array &$form, FormStateInterface $form_state) {
  return os2loop_documents_add_document_set($form, $form_state);
}

/**
 *
 */
function os2loop_documents_build_document_tree(array &$form, FormStateInterface $form_state, NodeInterface $node) {
  $form['documents_label'] = [
    '#type' => 'label',
    '#title' => t('Documents'),
  ];

  $form['documents'] = [
    '#type' => 'container',
    '#title' => t('Documents'),
    '#prefix' => '<div id="collection-documents-wrapper">',
    '#suffix' => '</div>',
  ];

  $form['documents']['tree'] = [
    // '#weight' => 200,
    '#type' => 'table',
    // '#header' => [
    //   t('Name'),
    //   t('Actions'),
    //   t('Weight'),
    //   t('Parent'),
    // ],
    '#empty' => t('No documents added yet.'),
    // TableDrag: Each array value is a list of callback arguments for
    // drupal_add_tabledrag(). The #id of the table is automatically
    // prepended; if there is none, an HTML ID is auto-generated.
    '#tabledrag' => [
      [
        'action' => 'match',
        'relationship' => 'parent',
        'group' => 'row-pid',
        'source' => 'row-id',
        'hidden' => TRUE, /* hides the WEIGHT & PARENT tree columns below */
        'limit' => FALSE,
      ],
      [
        'action' => 'order',
        'relationship' => 'sibling',
        'group' => 'row-weight',
      ],
    ],
  ];


  $form['actions']['submit']['#submit'][] = 'os2loop_documents_documents_submit';
  // $form['#validate'][] = 'os2loop_documents_documents_validate';
  // array_unshift($form['#submit'], 'os2loop_documents_documents_submit');

  // $form['os2loop_documents_documents']['#type'] = 'hidden';
  // @see https://drupal.stackexchange.com/questions/267347/change-value-on-validate-form-when-i-create-or-edit-a-block#comment365273_267441
  // $form['os2loop_documents_documents']['widget'][0]['#element_validate'][] = 'os2loop_documents_documents_validate';

  // $form['os2loop_documents_documents']['widget'][0]['value']['#value'] = 'os2loop_documents_documents_validate';
  $form['documents']['add_document'] = [
    '#type' => 'container',
    '#attributes' => ['class' => ['container-inline']],
    // '#weight' => 100,
    '#prefix' => '<div id="loop-documents-add-document">',
    '#suffix' => '</div>',
  ];

  $form['documents']['add_document']['document'] = [
    '#type' => 'entity_autocomplete',
    '#target_type' => 'node',
    '#selection_settings' => [
      'target_bundles' => ['os2loop_documents_document'],
    ],
    '#prefix' => '<div id="loop-documents-menu-document-options">',
    '#suffix' => '</div>',
  ];

  $form['documents']['add_document']['message'] = [
    '#markup' => '',
  ];

  $form['documents']['add_document']['actions']['submit'] = [
    '#type' => 'submit',
    '#submit' => ['os2loop_documents_add_document_submit'],
    // @see https://www.drupal.org/docs/drupal-apis/ajax-api/basic-concepts#sub_form
    '#ajax' => [
      'callback' => 'os2loop_documents_add_document_set',
      'wrapper' => 'collection-documents-wrapper',
      'progress' => [
        'type' => 'throbber',
        'message' => NULL,
      ],
    ],
    '#value' => t('Add document'),
  ];

  // Build the table rows and columns.
  //
  // The first nested level in the render array forms the table row, on which
  // you likely want to set #attributes and #weight.
  // Each child element on the second level represents a table column cell in
  // the respective table row, which are render elements on their own. For
  // single output elements, use the table cell itself for the render element.
  // If a cell should contain multiple elements, simply use nested sub-keys to
  // build the render element structure for the renderer service as you would
  // everywhere else.
  // $results = self::getData();
  $results = os2loop_documents_get_collection_documents($form_state, $node);

  foreach ($results as $row) {
    // TableDrag: Mark the table row as draggable.
    $form['documents']['tree'][$row['id']]['#attributes']['class'][] = 'draggable';

    // Indent item on load.
    $indentation = [];
    if (isset($row['depth']) && $row['depth'] > 0) {
      $indentation = [
        '#theme' => 'indentation',
        '#size' => $row['depth'],
      ];
    }

    // Some table columns containing raw markup.
    $form['documents']['tree'][$row['id']]['name'] = [
      '#markup' => $row['name'],
      '#prefix' => !empty($indentation) ? render($indentation) : '',
    ];

    $form['documents']['tree'][$row['id']]['actions'] = [
      'remove' => [
        '#type' => 'submit',
        '#submit' => ['os2loop_documents_remove_document_submit'],
        '#ajax' => [
          'callback' => 'os2loop_documents_remove_document_set',
          'wrapper' => 'collection-documents-wrapper',
          'progress' => [
            'type' => 'throbber',
            'message' => NULL,
          ],
        ],
        // We must have unique values to make FormState::getTriggeringElement
        // work as expected.
        '#value' => t('Remove %document from collection', ['%document' => $row['name']]),
        '#attributes' => [
          'data-document-id' => $row['id'],
        ],
      ],
    ];

    // This is hidden from #tabledrag array (above).
    // TableDrag: Weight column element.
    $form['documents']['tree'][$row['id']]['weight'] = [
      '#type' => 'weight',
      '#title' => t('Weight for ID @id', ['@id' => $row['id']]),
      '#title_display' => 'invisible',
      '#default_value' => $row['weight'],
      // Classify the weight element for #tabledrag.
      '#attributes' => [
        'class' => ['row-weight'],
      ],
    ];
    $form['documents']['tree'][$row['id']]['parent']['id'] = [
      '#parents' => ['documents', $row['id'], 'id'],
      '#type' => 'hidden',
      '#value' => $row['id'],
      '#attributes' => [
        'class' => ['row-id'],
      ],
    ];
    $form['documents']['tree'][$row['id']]['parent']['pid'] = [
      '#parents' => ['documents', $row['id'], 'pid'],
      '#type' => 'number',
      '#size' => 3,
      '#min' => 0,
      '#title' => t('Parent ID'),
      '#default_value' => $row['pid'],
      '#attributes' => [
        'class' => ['row-pid'],
      ],
    ];
  }
}

// function os2loop_documents_documents_validate(array &$form, FormStateInterface $form_state) {
//   header('content-type: text/plain'); echo var_export(null, true); die(__FILE__.':'.__LINE__.':'.__METHOD__);
// }

function os2loop_documents_documents_submit(array &$form, FormStateInterface $formState) {
  $helper = \Drupal::service('os2loop_documents.collection_helper');
  $helper->updateCollection();
  header('content-type: text/plain'); echo var_export($formState->get('documents'), true); die(__FILE__.':'.__LINE__.':'.__METHOD__);
}

/**
 *
 */
function os2loop_documents_get_collection_documents(FormStateInterface $form_state, NodeInterface $node) {
  // $data = json_decode($node->os2loop_documents_documents->value, true);
  // $spec = $form_state->getValue('os2loop_documents_documents')[0]['value'] ?? '{}';
  // $data = json_decode($spec, TRUE);
  // if (!is_array($data)) {
  //   $data = [];
  // }
  $data = $form_state->get('documents') ?? [];
  $nodes = Node::loadMultiple(array_keys($data));
  foreach ($data as &$item) {
    if (0 == $item['pid']) {
      $item['depth'] = 0;
    }
    $node = $nodes[$item['id']] ?? NULL;
    $item['name'] = $node ? sprintf('%s (%s)', $node->getTitle(), $node->id()) : $item['id'];
  }

  foreach ($data as &$item) {
    if (!isset($item['depth'])) {
      $item['depth'] = $data[$item['pid']]['depth'] + 1;
    }
    if (!isset($item['weight'])) {
      $item['weight'] = 0;
    }
  }

  return $data;
}

/**
 *
 */
function os2loop_documents_documents_validate(array &$element, FormStateInterface $form_state) {
  // header('content-type: text/plain'); echo var_export($form_state->get('documents'), true); die(__FILE__.':'.__LINE__.':'.__METHOD__);
  // https://drupal.stackexchange.com/questions/267347/change-value-on-validate-form-when-i-create-or-edit-a-block#comment365273_267441
//  header('content-type: text/plain'); echo var_export($form_state->getValue(['documents', 'tree']), true); die(__FILE__.':'.__LINE__.':'.__METHOD__);
  // $form_state->setValueForElement($element, ['value' => json_encode($form_state->getValue('documents'))]);
}

/**
 * Ajax callback to add a document to a collection menu.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function os2loop_documents_add_document_callback(array $form, FormStateInterface $form_state) {
  $commands = [];
  $node = $form_state->getformObject()->getEntity();
  $menu_name = os2loop_documents_get_menu_name($node);
  $menu = os2loop_load_menu($menu_name);
  $target_node = NULL;
  $document_id = $form_state->getValue('document');
  if (!empty($document_id)) {
    $target_node = Node::load($document_id);
  }

  if ($node && $menu && $target_node) {
    $data = json_decode($form_state->getValue('os2loop_documents_documents')[0]['value'], TRUE);
    if (!is_array($data)) {
      $data = [];
    }
    $data[$target_node->id()] = [
      'weight' => 1000,
      'id' => $target_node->id(),
      'pid' => 0,
    ];
    $form_state->setValue('os2loop_documents_documents', ['value' => json_encode($data)]);
  }
  else {
    $commands[] = ajax_command_alert(t('Error adding document to collection'));
  }
}
